extends: substitution
message: "Use '%s' instead of '%s'."
level: warning
ignorecase: true
action:
  name: replace
swap:
  '(?<![\#-/])webforj(?![-/])': webforJ
  '(?<![\#-/])startforj(?![-/])': startforJ