name: Build WAR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-war:
    name: Build Java WAR File
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload WAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: target/*.war
