name: Java Playwright Tests

on:
  push:
    branches: [ playwright ]
  pull_request:
    branches: [ playwright ]
  workflow_dispatch:

jobs:
  test:
    name: 'Playwright Tests - Java'
    runs-on: ubuntu-22.04   # or use ubuntu-latest if preferred
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          java-package: jdk

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install project dependencies
        run: mvn clean install -DskipTests

      - name: Install Playwright browsers
        run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps"

      - name: Run tests
        run: mvn verify
        env:
          CI: true

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-test-results
          path: test-results/reports/
          retention-days: 14

      - name: Upload failure screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: failure-screenshots
          path: test-results/screenshots/
          retention-days: 14